config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  resources :articles
  resources :tags, only: %i[index show], param: :name
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  acts_as_taggable_on :tags

  validates :title, length: { maximum: 50 }, presence: true
  validates :body, length: { maximum: 2000 }, presence: true
  validate :validate_tag

  private

  TAG_MAX_COUNT = 5
  def validate_tag
    if tag_list.size > TAG_MAX_COUNT
      return errors.add(:tag_list, :too_many_tags, message: "は#{TAG_MAX_COUNT}つ以下にしてください")
    end

    tag_list.each do |tag_name|
      tag = Tag.new(name: tag_name)
      tag.validate_name
      tag.errors.messages[:name].each { |message| errors.add(:tag_list, message) }
    end
  end
end

app/models/tag.rb
class Tag < ActsAsTaggableOn::Tag
  validate :validate_name

  TAG_NAME_MAX_LENGTH = 30
  TAG_NAME_REGEX = /\A[\w一-龠々ぁ-ヶー]+\Z/.freeze
  def validate_name
    errors.add(:name, "は#{TAG_NAME_MAX_LENGTH}文字以内で入力してください") if name.length > TAG_NAME_MAX_LENGTH
    errors.add(:name, 'はひらがな、または全角のカタカナ、漢字、半角の英数字のみが使用できます') unless name.match?(TAG_NAME_REGEX)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  # GET /articles
  def index
    @articles = Article.all
  end

  # GET /articles/1
  def show; end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :body, :tag_list)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    tags = Tag.where('name LIKE ?', "%#{Tag.sanitize_sql_like(params[:name])}%").pluck(:name).first(5)
    render json: { message: 'Loaded tags', data: tags }, status: :ok
  end

  def show
    @tag = Tag.find_by(name: params[:name])
    raise ActiveRecord::RecordNotFound unless @tag

    @tagged_articles = Article.tagged_with(@tag.name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_articles.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td>
          <% article.tags.each do |tag| %>
            <%= link_to tag_path(tag.name) do %>
              <span class="tag"><%= tag %></span>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: 'label' %>
    <div class="control">
      <%= form.text_field :title, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :body, class: 'label' %>
    <div class="control">
      <%= form.text_area :body, class: 'textarea' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :tag_list, class: 'label' %>
    <div class="control">
      <%= form.text_field :tag_list, class: 'input height-unset custom-tagify-look', value: form.object.tag_list.to_s, pattern: '^[,a-z0-9一-龠々ぁ-ヶー]+$' %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: 'button' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Articles', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<%= render 'articles/articles', articles: @articles %>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Articles', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<p>
  <strong>Tags:</strong>
  <% @article.tags.each do |tag| %>
    <%= link_to tag_path(tag.name) do %>
      <span class="tag"><%= tag %></span>
    <% end %>
  <% end %>
</p>

<br>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Articles', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>tag-sandbox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <section class="section">
        <%= yield %>
      </section>
    </div>
  </body>
</html>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>
<p><%= "#{@tagged_articles.size}件の記事" %></p>

<%= render 'articles/articles', articles: @tagged_articles %>

<%= link_to 'Articles', articles_path %>